
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.55.248.13:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 120.55.248.13:8848
  application:
    name: gulimall-coupon
server:
  port: 8080